server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: 4-gateway
          uri: https://github.com/idevillafane/microservicio-chicas-superpoderosas/
          search-paths: config-data
  application:
    name: config-service
