server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: 2-config-server
          uri: git@github.com:idevillafane/microservicio-chicas-superpoderosas.git
          search-paths: config-data
  application:
    name: config-service
